name: export-from-dev-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: Agent1Solution
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
env:
  ENVIRONMENT_URL: ${{ vars.DEV_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  SOLUTION_FOLDER: out/solutions/
  SOLUTION_EXPORTED_FOLDER: out/exported/
  SOLUTION_TARGET_FOLDER: solutions/
  
permissions:
  contents: write
  
jobs:
  export-from-dev:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
     
    - name: Install Power Platform tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Validate connection
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ env.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Export solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ env.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ github.event.inputs.solution_name }}.zip

    - name: Unpack solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ env.SOLUTION_FOLDER }}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Branch solution to prepare for pull request
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: ${{ env.SOLUTION_FOLDER }}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ env.SOLUTION_TARGET_FOLDER }}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
