name: export-from-source-and-branch

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: Solution name to export
        required: true
        default: Agent1Solution

permissions:
  contents: write

jobs:
  export-from-dev-and-branch:
    runs-on: windows-latest

    env:
      SOLUTION_NAME: ${{ inputs.solution_name }}
      SOLUTION_EXPORTED_FOLDER: 'out/exported/'
      SOLUTION_FOLDER: 'out/solutions/'
      SOLUTION_TARGET_FOLDER: 'solutions/'
      POWER_PLATFORM_SOURCE_ENVIRONMENT_URL: ${{ secrets.POWER_PLATFORM_ALM_DEMOS_DEV_ENVIRONMENT_URL }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_ALM_DEMOS_DEV_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Power Platform tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Validate connection
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.POWER_PLATFORM_SOURCE_ENVIRONMENT_URL }}
          app-id: ${{ env.AZURE_CLIENT_ID }}
          client-secret: ${{ env.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          
      - name: Export unmanaged solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.POWER_PLATFORM_SOURCE_ENVIRONMENT_URL }}
          app-id: ${{ env.AZURE_CLIENT_ID }}
          client-secret: ${{ env.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}${{ github.event.inputs.solution_name }}.zip
          overwrite: true

      - name: Unpack unmanaged solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER }}${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ env.SOLUTION_FOLDER }}${{ github.event.inputs.solution_name }}
          solution-type: Unmanaged
          overwrite-files: true
          
      - name: Branch solution
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: ${{ env.SOLUTION_FOLDER }}${{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ env.SOLUTION_TARGET_FOLDER }}${{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
