name: on-workflow-dispatch-build-and-deploy-to-prod

on:
  workflow_dispatch:   
      
permissions:
  contents: write
  
jobs:
  build-and-deploy-to-prod:
    uses: ./.github/workflows/build-and-deploy-to-prod.yml
    with:
      solution_name: Agent1Solution
