name: release-to-target

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: Solution name to export
        required: true
        default: Agent1Solution

  release:
    types: [created]

env:
  SOLUTION_NAME: ${{ inputs.solution_name }}
  SOLUTION_SHIP_FOLDER: 'out/ship/'
  SOLUTION_SOURCE_FOLDER: 'solutions/'
  SOLUTION_RELEASE_FOLDER: 'out/release/'
  POWER_PLATFORM_SOURCE_ENVIRONMENT_URL: ${{ secrets.POWER_PLATFORM_ALM_DEMOS_DEV_ENVIRONMENT_URL }}
  POWER_PLATFORM_TARGET_ENVIRONMENT_URL: ${{ secrets.POWER_PLATFORM_ALM_DEMOS_DEV_ENVIRONMENT_URL }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_ALM_DEMOS_DEV_TENANT_ID }}

permissions:
  contents: write

jobs:
  create-artifacts:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true      

      - name: Install Power Platform tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Pack solution as managed
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-folder: ${{ env.SOLUTION_SOURCE_FOLDER }}/${{ github.event.inputs.solution_name }}
          solution-file: ${{ env.SOLUTION_SHIP_FOLDER }}/${{ github.event.inputs.solution_name }}.zip
          solution-type: Managed
          
      - name: Upload managed solution to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: managedSolutions
          path: ${{ env.SOLUTION_SHIP_FOLDER }}${{ github.event.inputs.solution_name }}.zip
