name: release-to-prod

on:
  workflow_dispatch:
    inputs:
      solution-name:
        required: true
        default: Agent1Solution
permissions:
  contents: write
  
jobs:
  release-to-prod:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Install Power Platform tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Download the managed solution to the artifact store
      uses: actions/download-artifact@v4
      with:
        name: managedSolutions
        path: out/release/
   
    - name: Import solution to destination environment
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ secrets.POWER_PLATFORM_ALM_DEMOS_GITHUB_ENVIRONMENT_URL }}
        app-id: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_ALM_DEMOS_DEV_TENANT_ID }}
        solution-file: out/release/${{ github.event.inputs.solution-name }}_managed.zip
        force-overwrite: true
        publish-changes: true
