name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: Agent1Solution
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orgcc787891.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://org4be935c8.crm.dynamics.com
      CLIENT_ID: 4cf7b7db-7a60-4b6b-9b26-0b56daec2a2a
      TENANT_ID: d51cb5af-080c-49c2-8bba-c288fca20773      
    secrets:  
      envSecret: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_SECRET }}
