name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  release-solution:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: Agent1Solution
      #Update your values here
    secrets:
      build_environment_url: ${{ secrets.POWER_PLATFORM_ALM_DEMOS_BUILD_ENVIRONMENT_URL }}
      production_environment_url: ${{ secrets.POWER_PLATFORM_ALM_DEMOS_GITHUB_ENVIRONMENT_URL }}
      client_id: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_ID }}
      client_secret: ${{ secrets.AZURE_ALM_DEMOS_DEV_CLIENT_SECRET }}
      tenant_id: ${{ secrets.AZURE_ALM_DEMOS_DEV_TENANT_ID }}      
